{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "sops-operator.roleKind" . }}
metadata:
  name: {{ include "sops-operator.fullname" . }}
  labels:
    {{- include "sops-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - craftypath.github.io
    resources:
      - sopssecrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - craftypath.github.io
    resources:
      - sopssecrets/finalizers
    verbs:
      - update
  - apiGroups:
      - craftypath.github.io
    resources:
      - sopssecrets/status
    verbs:
      - get
      - patch
      - update
{{- end }}
