apiVersion: v1
kind: Service
metadata:
  name: {{ include "sops-operator.fullname" . }}
  labels:
    {{- include "sops-operator.labels" . | nindent 4 }}
spec:
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "sops-operator.selectorLabels" . | nindent 4 }}
